#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

main() {
	local datetime_now  repo_path  repo_name
	datetime_now=$(date +'%Y-%m-%d-%H%M%S')
	repo_path="$(git rev-parse --show-toplevel)"
	repo_name="${repo_path##*/}"
	git bundle create "${repo_name}-${datetime_now}.bundle" --all
}

main "$@"

# vim:noet
