#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

usage() {
	printf >&2 "Usage: %s filename\n"  "${1}"
	exit 1
}

main() {
	if [ "${#}" -ne 1 ]; then
		usage "${0}"
	fi

	local filename="./${1}"
	if [ -f "${filename}" ]; then
		printf >&2 "Error: file/dir '%s' exists. Please run with another filename that does not exist.\n"  "${filename}"
		exit 1
	fi

	local org_cwd
	local path_to_script_dir
	org_cwd="$(pwd)"
	path_to_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
	cp "${path_to_script_dir}"/templates/bash "${filename}"
	chmod 0700 "${filename}"
	vim +'set noet' "${filename}"
}

main "$@"
# vim:noet
